[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_BASE_URL = "/"

# Configuração de produção
[context.production]
[[context.production.redirects]]
  from = "/api/*"
  to = "http://nerdplayer.tplinkdns.com:8090/api/:splat"
  status = 200
  force = true

# Configuração de preview/branch
[context.branch-deploy]
[[context.branch-deploy.redirects]]
  from = "/api/*"
  to = "http://localhost:8000/api/:splat"
  status = 200
  force = true